// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/finance-dashboard": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/finance-dashboard";
  };
  "routes/finance-dashboard.tsx": {
    id: "routes/finance-dashboard";
    page: "/finance-dashboard";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/finance-dashboard": typeof import("./app/routes/finance-dashboard.tsx");
  "routes/_index": typeof import("./app/routes/_index.tsx");
};